### ISSUE TITLE
建议将 ImageUploader 组件的 handleFileUpload 方法 暴露为一个接口

### ISSUE THREAD

**Issue by toutouli** [wowlusitong/re-editor#3]
现在处理 `image-local` 的方式是直接把图片转为Base64插入到内容里，这样会导致数据很大。

实际使用中我们可能会希望把图片上传到一个图片服务器，然后再通过一个地址来引用。
但是我看了一下源码，发现好像并没有提供相应的接口来定制上传文件的过程。

虽然我可以自己封装一个组件实现upload 的过程，然后把返回的地址通过`command(editor)('image',src)`的方式插入到内容里。但是图片的替换功能依然写死了是调用 `image-local` 的。

我觉得比较好的方式，是将 ImageUploader 组件的 handleFileUpload 方法暴露为一个接口。这样可以比较灵活的实现定制的上传过程。

**Comment by wowlusitong** [comment]
这周会给图片增加一个upload方法以支持图床和自定义上传功能。

**Comment by wowlusitong** [comment]
已增加自定义图片上传服务器功能 b72f0624b95513502908c7d5d4525efd452cad64
