### ISSUE TITLE
图片尺寸设置有问题

### ISSUE THREAD

**Issue by freedxz** [wowlusitong/re-editor#39]
目前在DEMO里上传一个图片，尺寸变形（宽度全宽高度不是按比例缩放），手工设置高宽时，高宽的输入框似乎不能获得焦点。

另外看看是否可能鼠标拉动缩放图片？

我的操作环境：MACOS + CHROME

**Comment by freedxz** [comment]
<img width="823" alt="屏幕快照 2019-07-29 下午5 45 23" src="https://user-images.githubusercontent.com/15033713/62038688-c4b2d100-b228-11e9-92b8-ae1cb18fe04a.png">

**Comment by wowlusitong** [comment]
@freedxz 多谢反馈
- 图片设置高宽的输入框不能获得焦点的问题已修复
- 鼠标拉动缩放图片功能已增加

https://github.com/wowlusitong/re-editor/releases/tag/v0.5.6
