### ISSUE TITLE
不是说，支持markdown语法吗？我试了，不支持呀

### ISSUE THREAD

**Issue by tgy3300** [wowlusitong/re-editor#4]
不是说，支持支持markdown语法吗？我试了，不支持呀，通不能讨论下

**Comment by wowlusitong** [comment]
暂时只是支持部分语法，如下：
- h1-h6: #
- 引用: >
- 有序列表: -
- 无序列表: 1.

表格，url，图片等目前是不支持的

https://github.com/wowlusitong/re-editor#%E5%85%B6%E4%BB%96

**Comment by tgy3300** [comment]
我在编辑器里直接输入

`# 这是一级标题`

也没有渲染成h1呀

**Comment by wowlusitong** [comment]
输入 `#`，然后按`空格`，就会将此行转为h1，下面为动图演示，或者在 https://re-editor.netlify.com/ 测试下是否好使

![Kapture 2019-05-04 at 20 33 31](https://user-images.githubusercontent.com/3221051/57179039-ed3a6180-6eab-11e9-8b18-a79f1da33006.gif)

**Comment by tgy3300** [comment]
哦，如果从其他md文件里复制markdown语法的文字内容，粘贴到编辑器里，能否会自动转呢

**Comment by wowlusitong** [comment]
> 哦，如果从其他md文件里复制markdown语法的文字内容，粘贴到编辑器里，能否会自动转呢

现在版本是不会的，可以增加这个功能

**Comment by tgy3300** [comment]
在哪里增加呢，请指点下，

**Comment by wowlusitong** [comment]
> 在哪里增加呢，请指点下，

是指后续版本会考虑增加这个功能支持~

**Comment by tgy3300** [comment]
希望出个开发教程，大家一起来完善这个编辑器

**Comment by wowlusitong** [comment]
> 希望出个开发教程，大家一起来完善这个编辑器

可以参考slate的文档，re-editor就是基于slate进行开发的，https://github.com/ianstormtaylor/slate
