### ISSUE TITLE
new features request

### ISSUE THREAD

**Issue by freedxz** [wowlusitong/re-editor#40]
图片：
1 建议图片初始按原图长宽比显示
2 图片用鼠标拉动缩放时，不要用角标拉（做得不够好），可以改成单纯拉高度和单纯拉宽度结合的方式
3 甚至进一步，用第三方 ‘react-image-crop’ 来弹出框，可以裁剪和旋转原图，截取选中部分来做结果图

保存和显示：
用json格式保存内容挺好，需要加一个显示结果的css或者独立react小组件，用来在需要显示结果的地方用来显示这个json内容。（用re-editor的只读模式可以做到，是不是可以更小巧些？）

**Comment by wowlusitong** [comment]
1. 现在应该就是按图片原始长宽显示的
2. 昨天临时做的，暂时是只支持等比缩放，有优化空间，后面可以增加支持单纯拉宽度和高度
3. 很好的建议 👍
4. 关于保存和显示，稍后可以提供一个html serialize，可以同时保存html https://github.com/wowlusitong/re-editor/issues/6

----

如果有好的实现方式，欢迎提PR，为开源项目贡献代码👏

**Comment by freedxz** [comment]
1 好👌可能我还是用这里的demo做的测试，没有拉新代码
2 如果是等比缩放，暂时也还好。额外提供单独拉高和拉宽是锦上添花。
3 这个组件我用过，只是还涉及到我用到的其他第三方的比如模态对话框来处理图片等，引入过多。我可能前端水平还不足以分离或者自己写模态对话框来完成处理
4 html serialize不建议吧，本来就不太适合用 dangerouslySetInnerHTML 来显示用户输入的内容，所以最好是存纯json，然后写组件来显示。

基于3提到的原因，我可能还贡献不了代码。

感谢你贡献

**Comment by freedxz** [comment]
好吧，我尝试一下。
已经fork， 可以的话再pull request给你

**Comment by fengyun2** [comment]
@wowlusitong 我也来提个建议：
1. 编辑器支持全屏编辑
2. 图片编辑宽高时，光标永远聚焦到最后，体验不好
3. 复制粘贴进来的含有图片的文本内容，图片全部丢失了
4. 编辑器最后可以有个字数限制的功能，可以实时反馈出当前文本还可以输入多少个文字
5. 可以选择输入的字体大小功能
6. 撤销和重做的图标建议修改一下，容易让人是图片旋转功能
7. 粘贴进来的图片是否可以提供接口上传到服务器呢？
8. 编辑器内容的左边最好能与工具栏左边对齐
9. 编辑器能否提供readonly或者disabled属性呢？

**Comment by wowlusitong** [comment]
@fengyun2 
1. 已增加全屏编辑功能 2dc6292 
7. 是支持上传到服务器的，[文档](https://github.com/wowlusitong/re-editor#%E5%A6%82%E4%BD%95%E6%8C%87%E5%AE%9A%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87%E6%9C%8D%E5%8A%A1%E5%99%A8)，也可参考demo [CustomUploadImageApp.js](https://github.com/wowlusitong/re-editor/blob/master/packages/examples/src/scripts/CustomUploadImageApp.js)
8. 可以试试样式覆盖
9. readonly是支持的，[查看props](https://github.com/wowlusitong/re-editor#props)

其他问题会陆续改善
