### ISSUE TITLE
删除所有内容后，再点击上传图片，无法展示图片

### ISSUE THREAD

**Issue by fengyun2** [wowlusitong/re-editor#41]
删除所有内容后，再点击上传图片，无法展示图片

**Comment by wowlusitong** [comment]
感谢反馈

**Comment by fengyun2** [comment]
@wowlusitong 感谢大佬提供更好的产品

**Comment by wowlusitong** [comment]
@fengyun2  https://github.com/wowlusitong/re-editor/releases/tag/v0.5.7  猜测是这个问题导致
