### ISSUE TITLE
支持选中图片后使用delete按键删除

### ISSUE THREAD

**Issue by tgy3300** [wowlusitong/re-editor#5]
https://re-editor.netlify.com/

我在上面官方给出的测试地址测试了，我现在在编辑器里输入了一段文字，**然后再上传一张图片，现在要把上传的这张图片放到其他位置是不行的，还有用backspace键删除图片会出错**

**Comment by wowlusitong** [comment]
- 目前版本是不支持通过拖拽等方式更改图片位置的，可以删除重新上传
- 删除图片有两个方法
  - 点击图片，然后点击图片工具栏的删除按钮
  - 光标在图片后面的时候可以使用backspace键删除，通过选中图片然后使用backspace删除还不支持，稍后会对这个功能进行处理的

![Kapture 2019-05-04 at 20 43 30](https://user-images.githubusercontent.com/3221051/57179196-afd6d380-6ead-11e9-9858-12bb89ca6c31.gif)

**Comment by wowlusitong** [comment]
Fixed by b218b998b6722ba95aa4eb673a5cd552e907a3c1
