### ISSUE TITLE
支持实现保存功能吗？看了下目前还没有这个功能

### ISSUE THREAD

**Issue by eWenly** [wowlusitong/re-editor#51]
编辑了之后需要保存

**Comment by wowlusitong** [comment]
提供onChange，就和保存input同理，https://github.com/wowlusitong/re-editor/blob/master/packages/examples/src/scripts/App.js#L23

**Comment by eWenly** [comment]
我知道你用的是localstorage来存value, 我想说的是类似一个按钮来出发保存文档

**Comment by wowlusitong** [comment]
localstorage只是为了演示，`保存按钮` 不属于富文本功能内，是跟随页面设计的，就像用input， textarea一样，已经提供了onChange
