### ISSUE TITLE
看完你的readerme，也没发现是怎么使用的，能不能详细点呢

### ISSUE THREAD

**Issue by aierweisi** [wowlusitong/re-editor#8]

**Comment by wowlusitong** [comment]
可以参考https://github.com/wowlusitong/re-editor/blob/master/packages/examples/src/scripts/App.js

readme确实简陋点，后面会写的详细些的

**Comment by aierweisi** [comment]
> 可以参考https://github.com/wowlusitong/re-editor/blob/master/packages/examples/src/scripts/App.js
> 
> readme确实简陋点，后面会写的详细些的
有没有讨论群啊，拉一下呗

**Comment by wowlusitong** [comment]
额....暂时还没群

**Comment by aierweisi** [comment]
搞一个呗，这样也能加大宣传力度，丁丁群和微信群都可以

**Comment by aierweisi** [comment]
> 额....暂时还没群

可以搞一个群吗？或者给一下联系方式

**Comment by wowlusitong** [comment]
@aierweisi 

<img width="200" src="https://user-images.githubusercontent.com/3221051/59003036-fae65c80-8846-11e9-9937-8cf517deeb47.JPG" />
